### ISSUE TITLE
Incomplete setup instructions

### ISSUE THREAD

**Issue by joeltperry** [awslabs/dynamodb-import-export-tool#1]
There aren't any instructions on how to create the jar file
And there's no instructions on how to provide my AWS credentials

**Comment by amcp** [comment]
You create the jar file by running `mvn install`. You can find the jar file in the target folder after running `mvn install`.

The default credential provider chain is used in the [implementation](https://github.com/awslabs/dynamodb-import-export-tool/blob/master/src/main/java/com/amazonaws/dynamodb/bootstrap/CommandLineInterface.java#L74), which means you can use any of the methods described in the [AWS SDK documentation](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) to pass credentials.

**Comment by joeltperry** [comment]
Thanks :)

**Comment by amcp** [comment]
You can use the following maven command to create and run the jar in one step: `mvn exec:java -Dexec.mainClass="com.amazonaws.dynamodb.bootstrap.CommandLineInterface"`
